plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/release-notes-generator"
    - writerOpts:
        # Customizing the commit format to include only the author username
        commitPartial: |
          - {{header}} ({{hash}}) by [@{{authorUsername}}]({{authorUrl}})
        # Customize footerPartial to list contributors by username
        footerPartial: |
          {{#if commitGroups}}
            ### Contributors
            {{#with @root.commitGroups}}
              {{#each commits}}
                {{#if authorUsername}}
                  - [@{{authorUsername}}]({{authorUrl}})
                {{/if}}
              {{/each}}
            {{/with}}
          {{/if}}
          {{> footer}}
  - "@semantic-release/github"
branches:
  - name: main
  - name: next
    prerelease: true
    channel: next
  - name: beta
    prerelease: true
    channel: beta
  - name: +([0-9])?(.{+([0-9]),x}).x}
