name: auto-release

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - docs/**

permissions:
  contents: write
  pull-requests: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_DRAFTER_SECRET }}
