name: semantic-lint

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: semantic-lint
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@fdd4d3ddf614fbcd8c29e4b106d3bbe0cb2c605d # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
